version: '3.8'
services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_fleetlens
      MYSQL_USER: fleetlens_user
      MYSQL_PASSWORD: fleetlens_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
    driver: local