server.port: 8080
spring:
  application.name: fleetlens-api
  datasource:
    url: ${DATASOURCE_URL:jdbc:mariadb://host.docker.internal:3306/db_fleetlens}
    username: ${DATASOURCE_USERNAME:fleetlens_user}
    password: ${DATASOURCE_PASSWORD:fleetlens_password}
    driver-class-name: ${DATASOURCE_DRIVER:org.mariadb.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update